### ISSUE TITLE
quiz 2

### ISSUE THREAD

**Issue by lzblack** [DanJamRod/mis3640#1]
Q2. almost there 
Q4. I totally agree with you that US system of measurements is anti-human :laughing:

**Comment by DanJamRod** [comment]
That q4 comment warms my heart :)

Just to clarify, is the comment for q2 from the initial quiz submit, or the post-class update? If it's the latter, is it that you want the keys to be ordered by when they get called rather than staying in their original order?

Thank you kindly!

**Comment by lzblack** [comment]
It is based on initial submission. Now it is perfect. 

More pythonic: `return (d)` -> `return d`
